#!/system/bin/sh
#
# (C) 2011 k0nane, ACS
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Library General Public License as published
# by the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>
#

#
# runtweaks (modified by thjap)
#

log -p i -t init:setprop "INIT.setprop BEGIN:tweaking settings"

if [ ! -e /data/local/animset ]
then
#	while [ ! -e /data/data/com.android.providers.settings/databases/settings.db ]
#		do
#			sleep 1
#	done
#	echo "running the tweak now"
#	echo "REPLACE INTO \"system\" VALUES(26,'window_animation_scale','0.5');REPLACE INTO \"system\" VALUES(27,'transition_animation_scale','0.5');" | sqlite3 /data/data/com.android.providers.settings/databases/settings.db
#	kill `pidof system_server`
#	echo "yes" > /data/local/animset
	if [ -e /data/data/com.android.providers.settings/databases/settings.db ]
	then
		echo "running the tweak now"
		echo "REPLACE INTO \"system\" VALUES(26,'window_animation_scale','0.25');REPLACE INTO \"system\" VALUES(27,'transition_animation_scale','0.25');" | sqlite3 /data/data/com.android.providers.settings/databases/settings.db
		kill `pidof system_server`
		echo "yes" > /data/local/animset
	fi
fi

log -p i -t init:setprop "INIT.setprop END:tweaking settings"
