#!/system/bin/sh
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Library General Public License as published
# by the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>
#

#
# mtree (modified by thjap)
#

log -p i -t init:mtree "INIT.mtree: BEGIN:performing filesystem init"

chmod 0777 /system
chmod 0777 /system/app
chmod 0777 /system/bin
chmod 0777 /system/etc
chmod 0777 /system/etc/bluetooth
chmod 0777 /system/etc/dhcpcd
chmod 0777 /system/etc/dhcpcd/dhcpcd-hooks
chmod 0777 /system/etc/firmware
chmod 0777 /system/etc/init.d
chmod 0777 /system/etc/permissions
chmod 0777 /system/etc/ppp
chmod 0777 /system/etc/security
chmod 0777 /system/etc/wifi
chmod 0777 /system/fonts
chmod 0777 /system/framework
chmod 0777 /system/lib
chmod 0777 /system/lib/bluez-plugin
chmod 0777 /system/lib/drm
chmod 0777 /system/lib/egl
chmod 0777 /system/lib/hw
chmod 0777 /system/lib/modules
chmod 0777 /system/lib/soundfx
chmod 0777 /system/media
chmod 0777 /system/media/audio
chmod 0777 /system/media/audio/camera
chmod 0777 /system/media/audio/ui
chmod 0777 /system/semc
chmod 0777 /system/semc/chargemon
chmod 0777 /system/semc/chargemon/data
chmod 0777 /system/usr
chmod 0777 /system/usr/icu
chmod 0777 /system/usr/keychars
chmod 0777 /system/usr/keylayout
chmod 0777 /system/usr/share
chmod 0777 /system/usr/share/bmd
chmod 0777 /system/usr/share/zoneinfo
chmod 0777 /system/xbin
chmod 0777 /data
chmod 0777 /data/app
chmod 0777 /data/app-private
chmod 0777 /data/dalvik-cache
chmod 0777 /data/data
chmod 0777 /data/secure

busybox find /sdcard/Android/data/com.cooliris.media/cache -type d -name "*-cache" -name "*-thumb" -exec rm -rf {} \;

log -p i -t init:mtree "INIT.mtree: END:performing filesystem init"
